version: '3.8'

services:
  # Static file server for HTML pages
  nginx:
    image: nginx:alpine
    ports:
      - "2080:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - presswire

  # Node.js API server for serverless functions
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=test
      - SMTP_PASS=test
    volumes:
      - ./api:/app/api
      - ./node_modules:/app/node_modules
    command: npm run dev
    networks:
      - presswire

  # Mock SMTP server for testing email verification
  mailhog:
    image: mailhog/mailhog
    ports:
      - "2025:8025"  # Web UI
      - "2026:1025"  # SMTP server
    networks:
      - presswire

  # Optional: Redis for session/cache storage
  redis:
    image: redis:alpine
    ports:
      - "2379:6379"
    networks:
      - presswire

networks:
  presswire:
    driver: bridge