#!/bin/bash

echo "🔍 Monitoring Netlify Build Activity"
echo "===================================="
echo ""
echo "Last commit:"
git log -1 --oneline
echo ""
echo "Check if [skip ci] is present:"
git log -1 --pretty=%B | grep -q "\[skip ci\]" && echo "✅ [skip ci] found - build should be skipped" || echo "❌ No [skip ci] - build will trigger"
echo ""
echo "To check build status:"
echo "1. Go to https://app.netlify.com/sites/majestic-cactus-4e1f49/deploys"
echo "2. If no new build appears = [skip ci] worked ✅"
echo "3. Current credits should remain at 1,000"
echo ""
echo "Build Credit Protection Status:"
echo "- PR saves use: /api/save-pr-no-build endpoint"
echo "- Commits include: [skip ci] prefix"
echo "- This preserves your 1,000 monthly credits"