[build]
  publish = "."
  functions = "api"
  # Only skip builds if ONLY news/ or pr/ directories changed
  # ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- ':!news/' ':!pr/'"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/news/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[context.production.environment]
  NODE_VERSION = "18"

[build.environment]
  # Tell Netlify's secret scanner to ignore these common env var values
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV,PORT"
  SECRETS_SCAN_ENABLED = "true"
  # Skip builds when only PR files change
  SKIP_PR_BUILDS = "true"